=== rjirovsky/pb138-videoweb/trunk/VideoWeb/web/WEB-INF/dvd.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">
        
    <xsd:element name="dvd-library" type="dvd-libraryType">
        <xsd:unique name="uniqueID">
            <xsd:selector xpath="dvd"/>
                <xsd:field xpath="@id"/>
        </xsd:unique>
    </xsd:element>
    
    <!-- KNIHOVNA -->
    <xsd:complexType name="dvd-libraryType">
        <xsd:sequence>
            <xsd:element name="dvd" type="dvdType" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <!-- DVD TYP -->
    <xsd:complexType name="dvdType">
        <xsd:all>
            <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1" />
            <xsd:element name="type" type="typeType" minOccurs="1" maxOccurs="1" />
            <xsd:element name="titles" type="titlesType" minOccurs="1" maxOccurs="1" />
        </xsd:all>
        <xsd:attribute name="id" type="xsd:unsignedLong" use="required"/>
    </xsd:complexType>

   <!-- VÝČET TYPŮ -->
   <xsd:simpleType name="typeType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="originál|časopis|domácí|kopie" />
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- TITULY -->
    <xsd:complexType name="titlesType">
        <xsd:sequence>
            <xsd:element name="title" type="titleType" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <!-- TITUL -->
    <xsd:complexType name="titleType">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1" />
            <xsd:element name="representative" type="xsd:string" minOccurs="0" maxOccurs="1" />
        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== rjirovsky/pb138-videoweb/trunk/VideoWeb/web/WEB-INF/dvd.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : dvd.xml
    Created on : April 25, 2011, 7:23 PM
    Author     : Adam
    Description:
        Purpose of the document follows.
-->
<dvd-library xsi:noNamespaceSchemaLocation="dvd.xsd" xmlns=""
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <dvd>
        <name>Dývko 1</name>
        <type>originál</type>
        <titles>
            <title>
                <name>Film 1</name>
                <representative>Herec filmu 1</representative>
            </title>
            <title>
                <name>Film 2</name>
                <representative>Herec filmu 2</representative>
            </title>
            <title>
                <name>Film 3</name>
                <representative>Herec filmu 3</representative>
            </title>
        </titles>
    </dvd>
    
    <dvd>
        <name>Dývko 2</name>
        <type>časopis</type>
        <titles>
            <title>
                <name>Časopis 1</name>
            </title>
            <title>
                <name>Časopis 2</name>
            </title>
        </titles>
    </dvd>
    
    <dvd>
        <name>Dývko 3</name>
        <type>domácí</type>
        <titles>
            <title>
                <name>Seriál</name>
            </title>
            <title>
                <name>Film</name>
                <representative>Herec filmu</representative>
            </title>
            <title>
                <name>Časopis</name>
            </title>
        </titles>
    </dvd>

    <dvd>
        <name>Dývko 4</name>
        <type>kopie</type>
        <titles>
            <title>
                <name>Seriál</name>
            </title>
            <title>
                <name>Film</name>
                <representative>Herec filmu</representative>
            </title>
            <title>
                <name>Časopis</name>
            </title>
        </titles>
    </dvd>
</dvd-library>
